### ISSUE TITLE
Account adress is not correct

### ISSUE THREAD

**Issue by MarianoAkaMery** [merigo-labs/solana-wallet-adapter#8]
when doing result.toJson()
the wallet address is not correct, also is possible to add new logo and make the library working for IOS?

**Comment by MarianoAkaMery** [comment]
child: TextButton(
                                            onPressed: () {
                                              // 2. Authorize application with wallet.
                                              adapter
                                                  .authorize()
                                                  .then((result) => setState(
                                                      () => _output =
                                                          result.toJson()))
                                                  .catchError((error) =>
                                                      setState(() =>
                                                          _output = error));
                                            },

**Comment by merigo-labs** [comment]
Hi Mariano,

On Android the address is base-64 encoded. The Account class has a toBase58() method to convert the base-64 address to base-58.

The Mobile Wallet Adapter Specification doesn't currently support iOS: [iOS Support](https://solana-mobile.github.io/mobile-wallet-adapter/spec/spec.html#ios).

**Comment by MarianoAkaMery** [comment]
Thank you so much, I have some other questions about the solana wallet mobile adapter, if you can help me reply it will help me a lot, would like to directly speak with you if possible too, since I see you are the only one working on solana with Flutter

**Comment by merigo-labs** [comment]
Shall we have a chat on Discord? What's your ID and when would be a good time to chat?

**Comment by MarianoAkaMery** [comment]
Username: meryakamariano
ID: 752231663173369877

Send me a message!
