### ISSUE TITLE
Unhandled Exception: Null check operator used on a null value

### ISSUE THREAD

**Issue by kevin-nemo74** [merigo-labs/solana-wallet-adapter#9]
when i try to connect using android 10 it gives an unhandled exception error but it works fine when i test it on a device thats running android 13
surprisingly it connects fine on phantom wallet but strugles through making a transaction but it doesnt connect at all for solflare 
but everything works fine on the android 13is there a way to fix that ? 

`E/flutter ( 5852): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
E/flutter ( 5852): #0      ConnectNavigationRouter.handleConnect (package:solflare/deeplink/navigation_router/connect/connect_navigation_router.dart:83)
E/flutter ( 5852): <asynchronous suspension>
E/flutter ( 5852): #1      ConnectNavigationRouter.handleConnectSagaDeeplink (package:solflare/deeplink/navigation_router/connect/connect_navigation_router.dart:171)
E/flutter ( 5852): <asynchronous suspension>
E/flutter ( 5852): #2      DeepLinkNavigationRouter.handleSagaDeepLink (package:solflare/deeplink/navigation_router/deep_link_navigation_router.dart:107)
E/flutter ( 5852): <asynchronous suspension>
E/flutter ( 5852): #3      MainCubit._handleMobileWalletAdapterIntent.<anonymous closure> (package:solflare/shared/bloc/main/main_cubit.dart:280)
E/flutter ( 5852): <asynchronous suspension>
E/flutter ( 5852): `

**Comment by kevin-nemo74** [comment]
Now its not working even in the android 13 can anyone tell me whats going on ?

**Comment by merigo-labs** [comment]
Hi Kevin,

What version of the adapter are you running?

**Comment by kevin-nemo74** [comment]
0.1.5 the latest i believe

**Comment by merigo-labs** [comment]
Thanks, I'll look at this tomorrow.

**Comment by kevin-nemo74** [comment]
Appreciate it.

**Comment by merigo-labs** [comment]
Hi Kevin,

When creating an instance of `SolanaWalletAdapter` I get the same error if I provide an empty `AppIdentity`. Try passing `AppIdentity` with a `uri` parameter.

```
final adapter = SolanaWalletAdapter(
    AppIdentity(
        uri: Uri.parse('https://my_dapp.com')
    ),
    ...
);
```

**Comment by kevin-nemo74** [comment]
Hey
Thank you your solution worked !
